# Generated by Django 3.2.21 on 2023-10-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_technical'),
        ('warehouse', '0002_alter_mritem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=10, verbose_name='شرج کالا'),
        ),
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, verbose_name='شماره PO')),
                ('date', models.DateField(blank=True, verbose_name='تاریخ درخواست')),
                ('company', models.CharField(max_length=100, verbose_name='شرکت فروشنده کالا')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='core.user', verbose_name='ثبت شده توسط')),
                ('mr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='warehouse.materialrequisition', verbose_name='شماره درخواست کالا')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='warehouse.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'سفارش خرید',
                'verbose_name_plural': 'سفارش های خرید',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='شماره')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='مقدار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poitems', to='warehouse.item', verbose_name='شرح کالا')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.procurementorder')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poitems', to='warehouse.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'قلم سفارش خرید',
                'verbose_name_plural': 'اقلام سفارش خرید',
            },
        ),
    ]
