# Generated by Django 3.2.21 on 2023-10-03 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_technical'),
        ('warehouse', '0003_auto_20231002_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200, verbose_name='شماره بارنامه')),
                ('company', models.CharField(max_length=100, verbose_name='شرکت فروشنده کالا')),
                ('date', models.DateField(blank=True, verbose_name='تاریخ درخواست')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pls', to='core.user', verbose_name='ثبت شده توسط')),
                ('mr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pls', to='warehouse.materialrequisition', verbose_name='شماره درخواست کالا')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pls', to='warehouse.procurementorder', verbose_name='شماره سفارش خرید کالا')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pls', to='warehouse.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'بارنامه',
                'verbose_name_plural': 'بارنامه ها',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='poitem',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Mr Item No.'),
        ),
        migrations.CreateModel(
            name='PLItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Mr Item No.')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='مقدار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plitems', to='warehouse.item', verbose_name='شرح کالا')),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.packinglist')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plitems', to='warehouse.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'قلم  بارنامه',
                'verbose_name_plural': 'اقلام بارنامه',
            },
        ),
    ]
